const members = [
  {
    id: 1,
    name: "Nur",
    age: 30,
    bloodType: "A+",
    readyToDonate: true,
    donationHistory: ["Rohim", "Korim", "Gofur"],
    location: "Dhanmondi",
    contactNumber: "01976559956",
    email: "nur@example.com",
  },

  {
    id: 2,
    name: "Naim",
    age: 33,
    bloodType: "A+",
    readyToDonate: true,
    donationHistory: ["Robin", "Kamal", "Goutom"],
    location: "Mirpur",
    contactNumber: "017765599560",
    email: "naim@example.com",
  },

  {
    id: 3,
    name: "Nipa",
    age: 25,
    bloodType: "A-",
    readyToDonate: true,
    donationHistory: ["Rajia", "Kona", "Golam"],
    location: "Dhanmondi",
    contactNumber: "018765599560",
    email: "nipa@example.com",
  },

  {
    id: 4,
    name: "Nabiha",
    age: 23,
    bloodType: "A+",
    readyToDonate: true,
    donationHistory: ["Ria", "Komoli", "Mim"],
    location: "Uttara",
    contactNumber: "019976559956",
    email: "nabiha@example.com",
  },

  {
    id: 5,
    name: "Rahim",
    age: 31,
    bloodType: "O+",
    readyToDonate: true,
    donationHistory: ["Rakib", "Kamal", "shorif"],
    location: "Ghulshan",
    contactNumber: "019765599560",
    email: "rahim@example.com",
  },

  {
    id: 6,
    name: "Karim",
    age: 27,
    bloodType: "A-",
    readyToDonate: true,
    donationHistory: ["Robbani", "Kayef", "Goljar"],
    location: "Mirpur",
    contactNumber: "014765599560",
    email: "karim@example.com",
  },

  {
    id: 7,
    name: "Jolil",
    age: 30,
    bloodType: "B+",
    readyToDonate: true,
    donationHistory: ["Rojob", "Kawsar", "Himel"],
    location: "Khilkhet",
    contactNumber: "015765599560",
    email: "jolil@example.com",
  },

  {
    id: 8,
    name: "Faruq",
    age: 29,
    bloodType: "AB+",
    readyToDonate: true,
    donationHistory: ["Rokon", "Kobir", "Goljar"],
    location: "Farmgate",
    contactNumber: "016765599560",
    email: "faruq@example.com",
  },

  {
    id: 9,
    name: "Farjana",
    age: 28,
    bloodType: "O-",
    readyToDonate: true,
    donationHistory: ["Rojel", "Komol", "Gim"],
    location: "Malibug",
    contactNumber: "019376559956",
    email: "farjana@example.com",
  },

  {
    id: 10,
    name: "Hasan",
    age: 26,
    bloodType: "A-",
    readyToDonate: true,
    donationHistory: ["Rohman", "Kajol", "Gia"],
    location: "Toggi",
    contactNumber: "01476559956",
    email: "hasan@example.com",
  },

  {
    id: 11,
    name: "Nusrat",
    age: 22,
    bloodType: "B+",
    readyToDonate: true,
    donationHistory: ["Ria", "Kamar", "Gif"],
    location: "Jattarabari",
    contactNumber: "019176559956",
    email: "nusrat@example.com",
  },

  {
    id: 12,
    name: "Jamal",
    age: 30,
    bloodType: "AB+",
    readyToDonate: true,
    donationHistory: ["Rojel", "Kobirul", "Giash"],
    location: "Gabtoli",
    contactNumber: "0191176559956",
    email: "jamal@example.com",
  },

  {
    id: 13,
    name: "Rejaul",
    age: 19,
    bloodType: "A-",
    readyToDonate: true,
    donationHistory: ["Robin", "Kamru", "Hasib"],
    location: "Abdullahpur",
    contactNumber: "019976559956",
    email: "rejaul@example.com",
  },

  {
    id: 14,
    name: "Jalal",
    age: 31,
    bloodType: "A+",
    readyToDonate: true,
    donationHistory: ["Robbani", "Kamrujjaman", "Sihab"],
    location: "Uttora",
    contactNumber: "019776559960",
    email: "jalal@example.com",
  },

  {
    id: 15,
    name: "Rubel",
    age: 35,
    bloodType: "Ab+",
    readyToDonate: true,
    donationHistory: ["Rojel", "Sujon", "Akash"],
    location: "Komlapur",
    contactNumber: "019756559560",
    email: "rubel@example.com",
  },

  {
    id: 16,
    name: "Bipa",
    age: 28,
    bloodType: "O+",
    readyToDonate: true,
    donationHistory: ["Shimu", "Ria", "Roji"],
    location: "Banani",
    contactNumber: "01974455990",
    email: "bipa@example.com",
  },

  {
    id: 17,
    name: "Taher",
    age: 39,
    bloodType: "A+",
    readyToDonate: true,
    donationHistory: ["Babu", "Aminur", "Shima"],
    location: "Ajimpur",
    contactNumber: "01976500560",
    email: "taher@example.com",
  },

  {
    id: 18,
    name: "Tumppa",
    age: 26,
    bloodType: "A-",
    readyToDonate: true,
    donationHistory: ["Nil", "Bipu", "Jami"],
    location: "Gulistan",
    contactNumber: "0199955990",
    email: "tumppa@example.com",
  },

  {
    id: 19,
    name: "Habib",
    age: 32,
    bloodType: "Ab-",
    readyToDonate: true,
    donationHistory: ["Hasibul", "Ripon", "Minali"],
    location: "Kallanpur",
    contactNumber: "0188855995",
    email: "habib@example.com",
  },

  {
    id: 20,
    name: "Biplob",
    age: 28,
    bloodType: "A+",
    readyToDonate: true,
    donationHistory: ["Eliyas", "Dip", "Sohel"],
    location: "Motijhil",
    contactNumber: "01666599560",
    email: "biplob@example.com",
  },
];
